name: pre-release

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'webpack.config.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run lint
      - run: npm test

  pre-release:
    name: 'Pre Release'
    needs: test
    if: >-
      ${{ github.event_name == 'push' && contains(github.event.commits.*.added, 'src/') || contains(github.event.commits.*.modified, 'src/') || contains(github.event.commits.*.removed, 'src/') }} ||
      ${{ github.event_name == 'push' && contains(github.event.commits.*.added, 'public/') || contains(github.event.commits.*.modified, 'public/') || contains(github.event.commits.*.removed, 'public/') }} ||
      ${{ github.event_name == 'push' && contains(github.event.commits.*.added, 'package.json') || contains(github.event.commits.*.modified, 'package.json') || contains(github.event.commits.*.removed, 'package.json') }} ||
      ${{ github.event_name == 'push' && contains(github.event.commits.*.added, 'package-lock.json') || contains(github.event.commits.*.modified, 'package-lock.json') || contains(github.event.commits.*.removed, 'package-lock.json') }} ||
      ${{ github.event_name == 'push' && contains(github.event.commits.*.added, 'webpack.config.js') || contains(github.event.commits.*.modified, 'webpack.config.js') || contains(github.event.commits.*.removed, 'webpack.config.js') }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - name: zip
        run: zip -r copy-url.zip copy-url
      - uses: softprops/action-gh-release@v1
        with:
          name: 'Development Build'
          draft: true
          prerelease: true
          generate_release_notes: true
          files: copy-url.zip
